# Generated by Django 3.2.9 on 2021-11-22 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Raffle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id', models.CharField(default='', max_length=39)),
                ('name', models.CharField(blank=True, max_length=155, null=True, verbose_name='Sorteio')),
                ('ticket_amount', models.PositiveIntegerField(default=1, verbose_name='Quantidade de tickets')),
                ('ticket_price', models.FloatField(default=1, verbose_name='Preço do ticket')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Data do sorteio')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='photos/', verbose_name='Foto de capa')),
                ('photo_1', models.ImageField(blank=True, null=True, upload_to='photos/', verbose_name='Foto 1')),
                ('photo_2', models.ImageField(blank=True, null=True, upload_to='photos/', verbose_name='Foto 2')),
                ('photo_3', models.ImageField(blank=True, null=True, upload_to='photos/', verbose_name='Foto 3')),
                ('photo_4', models.ImageField(blank=True, null=True, upload_to='photos/', verbose_name='Foto 4')),
                ('info', models.CharField(blank=True, max_length=255, null=True, verbose_name='Informações do sorteio')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('status', models.CharField(choices=[('ACT', 'Ativo'), ('INA', 'Inativo'), ('SOO', 'Em breve')], default='SOO', max_length=20)),
            ],
            options={
                'verbose_name': 'Sorteio',
                'verbose_name_plural': 'Sorteios',
                'ordering': ('status',),
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('AVA', 'Disponível'), ('RES', 'Reservado'), ('PAI', 'Pago')], default='RES', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data de reserva')),
                ('ticket_number', models.PositiveIntegerField(verbose_name='Número')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome')),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('_id', models.CharField(default='', max_length=39)),
                ('phone', models.CharField(blank=True, max_length=30, null=True, verbose_name='Telefone')),
                ('instagram', models.CharField(blank=True, max_length=255, null=True)),
                ('raffle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='raffles.raffle', verbose_name='Sorteio')),
            ],
            options={
                'ordering': ['ticket_number'],
                'unique_together': {('raffle', 'ticket_number')},
            },
        ),
    ]
