# Generated by Django 3.2.9 on 2021-11-25 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raffles', '0002_auto_20211122_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raffle',
            name='info',
            field=models.TextField(blank=True, null=True, verbose_name='Informações do sorteio'),
        ),
        migrations.AlterUniqueTogether(
            name='ticket',
            unique_together=set(),
        ),
    ]
