# Generated by Django 3.2.9 on 2021-11-30 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raffles', '0004_ticket_cpfcnpj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raffle',
            name='name',
            field=models.CharField(max_length=155, verbose_name='Sorteio'),
        ),
    ]
